### PR TITLE
Download Dependencies and create Eclipse project

### PR DESCRIPTION
**Pull request by jakiki6**
Note: It is not fully working yet (Eclipse is a little bit annoying)

### CODE REVIEW

**Comment by hube12** [comment]
The changes looks ok to me, shall i test it or is it not finished ?

**Comment by jakiki6** [comment]
The problem is that both decompilers generate code that isn't fully compatible with that what Eclipse wants to see. So the part with Eclipse isn't fully working yet

**Comment by extremeheat** [comment]
The patches you need can be found in https://github.com/MinecraftForge/MCPConfig/blob/master/versions/release (maybe these can be obtained through a submodule).

If you map between mojang <-> mcp SRGs it should be possible to apply those patches from Forge to the Mojang mappings if using fernflower.

**Comment by ajloveslily14** [comment]
This fails to download dependencies on windows because when `download_file` gets called with a file name like `libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar` and then tries to split it using `os.path.sep` while making the directories it doesn't get split because the separator for windows is `\`. This can be fixed though but literally just changing it to `/` os.makedirs works fine using `/` on windows. So in effect, line 102 can just be made
`os.makedirs("/".join(filename.split("/")[:filename.count("/")]), exist_ok=True)` to fix the issue

**Comment by hube12** [comment]
Too old

**Pull request closed without merging**
