### PR TITLE
Make main.py executable

### PR DESCRIPTION
**Pull request by dhouck**
As in the title

### CODE REVIEW

**Comment by dhouck** [comment]
Wow, github does not display mode changes well.  This is not an empty file and I did not empty the file; the *diff* is empty because I didn't change the content.

**Comment by hube12** [comment]
Setting a chmod or suid bit is not a valid PR as git will strip it down anyway. This should be done per user by using chmod +x main.py locally

**Comment by dhouck** [comment]
Git does store the executable bit, although it doesn't store most of the rest of the perms.

On GitHub, this PR has:
image
Note the `100644 → 100755`.

On git CLI, I have
```
commit f2ab052 (HEAD -> executable-perms, origin/executable-perms, master)
Author:     Daniel Houck <GitHub@DRHouck.me>
AuthorDate:  Thu 2021-06-03 4:04:21 -0500
Commit:     Daniel Houck <GitHub@DRHouck.me>
CommitDate:  Thu 2021-06-03 4:04:21 -0500

    Make main.py executable

diff --git a/main.py b/main.py
old mode 100644
new mode 100755
```

I don't know if it'll eat it if you commit from Windows but I expect not.

**Comment by hube12** [comment]
My point was my system whether I am on windows on linux will strip the perms bit. I don't consider this a valid PR because you should not push executable files on source, I could add it as a release tho

**Pull request closed without merging**
